site_name: Probato Framework
site_url: https://probato.org
repo_url: https://github.com/probato-team/probato
repo_name: probato-team/probato
remote_branch: main

docs_dir: src
site_dir: docs

copyright: >
  <p>Copyright &copy; 2024–
  <script>document.write(new Date().getFullYear())</script>
  Probato</p>

theme:
  name: material
  logo: assets/images/probato-logo.png
  favicon: assets/images/favicon.ico

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    alternate: material/web

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.prune
    - navigation.footer
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - announce.dismiss

# ----------------------
# Navigation (EN default)
# ----------------------
nav:
  - Home:
      - Overview: index.md
      - Objective: objective.md
      - Target Audience: target-audience.md
      - Features: features.md
      - Architecture: architecture.md

  - Concepts:
      - Overview: concepts/index.md
      - Suite: concepts/suite.md
      - Script: concepts/script.md
      - Procedure: concepts/procedure.md
      - Page Object: concepts/page-object.md
      - Dataset: concepts/dataset.md
      - Database: concepts/database.md

  - Documentation: 
      - Introduction: documentation\index.md
      - Environment Configuration: documentation\environment-configuration.md
      - Project Creation: documentation\project-creation.md
      - Project Configuration: documentation\project-configuration.md
      - Browser Configuration: documentation\browser-configuration.md
      - Suite Implementation: documentation\suite-implementation.md
      - Script Implementation: documentation\script-implementation.md
      - Procedure Implementation: documentation\procedure-implementation.md
      - Page Object Implementation: documentation\page-object-implementation.md
      - Dataset Implementation: documentation\dataset-implementation.md
      - Database Implementation: documentation\database-implementation.md
      - Example: documentation\example.md

  - Probato Manager: manager/index.md

  - About:
      - About the Project: about/index.md

# ----------------------
# Plugins
# ----------------------
plugins:
  - search
  - git-revision-date
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          build: true
          site_name: Probato Framework

        - locale: pt-BR
          name: Português (Brasil)
          build: true
          site_name: Probato Framework
          nav_translations:

            # Home
            Home: Início
            Overview: Visão geral
            Objective: Objetivo
            Target Audience: Público Alvo
            Features: Recursos
            Architecture: Arquitetura

            Concepts: Conceitos
            Suite: Suite
            Script: Script
            Procedure: Procedure
            Page Object: Page Object
            Dataset: Dataset
            Database: Database

            Documentation: Documentação
            Introduction: Introdução
            Environment Configuration: Configuração de Ambiente
            Project Creation: Criação de projeto
            Project Configuration: Configuração do Projeto
            Browser Configuration: Configuração de Browser
            Suite Implementation: Implementação de Suite
            Script Implementation: Implementação de Script
            Procedure Implementation: Implementação de Procedure
            Page Object Implementation: Implementação de Page Object
            Dataset Implementation: Implementação de Dataset
            Database Implementation: Implementação de Database
            Example: Exemplo

            Probato Manager: Probato Manager
            
            About: Sobre
            About the Project: Sobre o Projeto

# ----------------------
# Extra
# ----------------------
extra:
  alternate:
    - name: English
      link: /
      lang: en
      icon: material/flag-outline

    - name: Português
      link: /pt-BR/
      lang: pt-BR
      icon: material/flag

  analytics:
    provider: google
    property: G-XZR907P520

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/probato-team/probato

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@probato

extra_css:
  - assets/css/custom.css
  - assets/css/extra.css

markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html

  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

  - pymdownx.tasklist:
      custom_checkbox: true
